name: yarm

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 24.x
        uses: actions/setup-node@v3
        with:
          node-version: 24.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      # - name: Run tests
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: test run

      - name: Type check
        uses: borales/actions-yarn@v4
        with:
          cmd: typecheck

      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint

      - name: Check code format
        uses: borales/actions-yarn@v4
        with:
          cmd: format:check

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build